# Generated by Django 3.2.6 on 2021-08-21 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchedVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100, verbose_name='Usuário')),
                ('title', models.CharField(max_length=255, verbose_name='Título Vídeo')),
            ],
        ),
    ]
