# Generated by Django 3.2.6 on 2021-08-22 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
        ('videos', '0002_watchedvideo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videos',
            options={'ordering': ['watched_at'], 'verbose_name': 'Videos', 'verbose_name_plural': 'Videos'},
        ),
        migrations.AddField(
            model_name='videos',
            name='curso',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cursos.cursos'),
            preserve_default=False,
        ),
    ]
