# Generated by Django 3.2.6 on 2021-08-22 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_auto_20210822_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videos',
            name='curso',
        ),
    ]
