# Generated by Django 3.2.6 on 2021-09-06 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_videos_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='segundos',
            field=models.IntegerField(blank=True, default=0, verbose_name='Segundos'),
            preserve_default=False,
        ),
    ]
