# Generated by Django 3.2.6 on 2021-11-18 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_videos_segundos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videos',
            options={'ordering': ['created_at'], 'verbose_name': 'Videos', 'verbose_name_plural': 'Videos'},
        ),
        migrations.RenameField(
            model_name='videos',
            old_name='watched_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='watchedvideo',
            name='curso',
            field=models.CharField(default='', max_length=255, verbose_name='Curso Vídeo'),
            preserve_default=False,
        ),
    ]
