# Generated by Django 3.2.6 on 2021-11-18 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_auto_20211117_2139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videos',
            options={'ordering': ['watched_at'], 'verbose_name': 'Videos', 'verbose_name_plural': 'Videos'},
        ),
        migrations.RenameField(
            model_name='videos',
            old_name='created_at',
            new_name='watched_at',
        ),
    ]
