# Generated by Django 3.2.6 on 2022-01-02 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='curso',
            field=models.CharField(default='', max_length=255, verbose_name='Curso'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forum',
            name='user',
            field=models.CharField(default='', max_length=255, verbose_name='Usuário'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='forum',
            name='content',
            field=models.TextField(blank=True, verbose_name='Conteúdo'),
        ),
    ]
