# Generated by Django 3.2.6 on 2021-11-18 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressoCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100, verbose_name='Usuário')),
                ('curso', models.IntegerField(verbose_name='Id Curso')),
                ('progresso', models.FloatField(verbose_name='Progresso Curso')),
            ],
        ),
    ]
